image: Visual Studio 2017

platform:
  - x64
environment:
  GH_TOKEN:
      secure: 6c8504feed4c29ad99c1ffb625aa821c37acdc91
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 8 x64
  - yarn
build_script:
  - yarn dist:windows
test: off
