os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: 6c8504feed4c29ad99c1ffb625aa821c37acdc91
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node 13.10.1
  - set CI=true
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn dist:windows
