image: Visual Studio 2019

platform:
  - x64
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 12.17.0 x64
  - yarn
build_script:
  - yarn dist:windows
artifacts:
  - path: dist\StreamJam-*.zip
    name: streamjam
deploy:
  release: streamjam-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token: ${GITHUB_TOKEN}
  artifact: streamjam
  draft: false
  prerelease: false
  on:
    branch: master
test: off
